import yfinance as yf
import pandas as pd
import numpy as np
import logging

from config.settings import TRANSACTION_FEE, TRANSACTION_TAX

logger = logging.getLogger(__name__)

class BacktestEvaluator:
    def __init__(self, start_date: str = "2022-01-01", end_date: str = "2025-12-31"):
        self.start_date = start_date
        self.end_date = end_date
        self.tx_cost = TRANSACTION_FEE + TRANSACTION_TAX
        
    def fetch_benchmark(self) -> pd.DataFrame:
        """
        Fetch 0050.TW (Taiwan 50 ETF) as the benchmark for buy-and-hold strategy
        """
        logger.info(f"Fetching 0050.TW as benchmark from {self.start_date} to {self.end_date}...")
        try:
            benchmark = yf.download("0050.TW", start=self.start_date, end=self.end_date)
            
            # Buy and hold return calculation
            if not benchmark.empty:
                initial_price = benchmark['Close'].iloc[0].item() if hasattr(benchmark['Close'].iloc[0], 'item') else float(benchmark['Close'].iloc[0])
                final_price = benchmark['Close'].iloc[-1].item() if hasattr(benchmark['Close'].iloc[-1], 'item') else float(benchmark['Close'].iloc[-1])
                
                total_return = (final_price - initial_price) / initial_price
                annualized_return = (1 + total_return) ** (252 / len(benchmark)) - 1
                
                logger.info(f"Benchmark (0050) Total Return: {total_return*100:.2f}%")
                return {
                    'total_return': total_return,
                    'annualized_return': annualized_return,
                    'initial_price': initial_price,
                    'final_price': final_price
                }
        except Exception as e:
            logger.error(f"Error fetching benchmark: {e}")
        return {}

    def run_strategy_backtest(self, mock_trades: list):
        """
        Simulate the strategy performance over time using a list of mock trades.
        mock_trades is a list of dicts:
        [{'ticker': '2330', 'entry_date': '...', 'exit_date': '...', 'entry_price': 100, 'exit_price': 120}, ...]
        """
        # Note: In a full pipeline, this would iterate day-by-day, predict, buy, and sell.
        # This is the simplified evaluator engine that calculates metrics from trade records.
        
        if not mock_trades:
            logger.warning("No trades provided for backtest.")
            return {}
            
        total_pnl_pct = 0.0
        winning_trades = 0
        total_trades = len(mock_trades)
        
        for trade in mock_trades:
            # Gross Return
            ret = (trade['exit_price'] - trade['entry_price']) / trade['entry_price']
            
            # Net Return (Deducting buy fee and sell fee+tax)
            net_ret = ret - (self.tx_cost * 2) # approx: cost on buy and cost on sell
            
            total_pnl_pct += net_ret
            if net_ret > 0:
                winning_trades += 1
                
        win_rate = winning_trades / total_trades if total_trades > 0 else 0
        
        logger.info(f"--- Strategy Backtest Results ---")
        logger.info(f"Total Trades: {total_trades}")
        logger.info(f"Win Rate: {win_rate*100:.2f}%")
        logger.info(f"Cumulative Net Return (Sum of non-compounded trades): {total_pnl_pct*100:.2f}%")
        
        return {
            'total_trades': total_trades,
            'win_rate': win_rate,
            'cumulative_net_return': total_pnl_pct
        }

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    evaluator = BacktestEvaluator()
    
    # 1. Evaluate Benchmark (0050 Buy and Hold)
    evaluator.fetch_benchmark()
    
    # 2. Simulate Strategy Backtest
    # This is a mocked list of trades for architectural validation
    mocked_strategy_trades = [
        {'ticker': '2330.TW', 'entry_date': '2022-01-05', 'exit_date': '2022-01-12', 'entry_price': 650, 'exit_price': 660},
        {'ticker': '2317.TW', 'entry_date': '2022-02-10', 'exit_date': '2022-02-17', 'entry_price': 105, 'exit_price': 102}, # Loss
        {'ticker': '2454.TW', 'entry_date': '2022-03-01', 'exit_date': '2022-03-08', 'entry_price': 900, 'exit_price': 960},
        # ... generated by combining fetching -> modeling -> signals in a loop.
    ]
    
    evaluator.run_strategy_backtest(mocked_strategy_trades)
