-- =======================================================
-- Project Chronos - Supabase Database Schema
-- 請將此腳本貼上至 Supabase 的 SQL Editor 執行
-- =======================================================

-- 1. Users 表格：記錄每個使用者的虛擬本金
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT PRIMARY KEY,
    balance NUMERIC DEFAULT 1000000.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Holdings 表格：記錄使用者的持股庫存
CREATE TABLE IF NOT EXISTS holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    ticker TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    avg_price NUMERIC NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, ticker)
);

-- 3. Trades 表格：記錄使用者的交易明細
CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    ticker TEXT NOT NULL,
    action TEXT NOT NULL, -- 'BUY' or 'SELL'
    price NUMERIC NOT NULL,
    quantity INTEGER NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Subscribers 表格：記錄訂閱每日推播的使用者 ID
CREATE TABLE IF NOT EXISTS subscribers (
    chat_id BIGINT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. DailyStates 表格：記錄 AI 每日盤前預測與明日觀測標的
CREATE TABLE IF NOT EXISTS daily_states (
    date_str TEXT PRIMARY KEY, -- 格式: YYYY-MM-DD 或 'tomorrow_target'
    ticker TEXT,
    predictions JSONB,
    pm_view TEXT,
    morning_price NUMERIC,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 設定權限 (Row Level Security)，為了簡單起見，如果是透過 Service Key 存取可忽略
-- 但為確保安全，建議開啟 RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE holdings ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_states ENABLE ROW LEVEL SECURITY;

-- 允許 Anon Key (或 Service Role) 讀寫 (若後端用 python SDK 且給 anon key，需建立 Policy)
-- 這裡為了 Python 後台方便直接操作，我們允許 authenticated 存取，或直接使用 Service Key。
-- 如果您的 Python bot 是使用 Service Role Key (secret key)，它會直接繞過 RLS，
-- 所以不用特別設定 Policy 也沒關係！
